version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - python -m pip install --upgrade pip
      - pip install poetry
    post_install:
      - poetry config virtualenvs.create false
      - poetry install --with dev

sphinx:
  configuration: docs/_source/conf.py
